# Generated by Django 5.2.4 on 2025-08-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryrequest',
            name='ai_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryrequest',
            name='servings_per_meal',
            field=models.IntegerField(default=1),
        ),
    ]
